Remove selenium and bump python-telegram-bot lib
yymin1022/KakaoEmoticon2TelegramSticker pull request #7
Opened 2023-10-25 05:31 UTC by Coder-Iro

2023-10-25 05:54 UTC, yymin1022 commented
PR 내용을 [예시](https://github.com/yymin1022/Wa_API/pull/115) 처럼 맞춰주시기 바랍니다.

2023-10-25 07:36 UTC, Coder-Iro commented
테스트를 몇번 해본 결과로는 네트워크쪽 최적화를 많이 했는데도 불구하고 속도가 심각하게 느리네요..
https://core.telegram.org/bots/api#using-a-local-bot-api-server 를 한번 써봐야될거같은데..

2023-10-26 23:27 UTC, Coder-Iro commented
업로드 속도가 너무 느려서 Vultr 독일 리전이랑 GCP 영국 리전에서도 테스트를 해봤는데 딱히 서버 위치가 가깝다고해서 빨라지거나 하지는 않네요. 텔레그램 API 서버 응답속도가 원래 느린거같은데...

2023-10-30 16:15 UTC, yymin1022 requested changes
전체적인 코드의 동작을 확인하고, 로직 이슈를 체크해보았습니다.
언급하신 속도 이슈의 경우에는 기존 버전에서도 꽤나 느린 편이었던 것을 감안하면, 새로 작업해주신 버전도 충분히 사용성은 비슷한 결과로 보이는 것 같네요.
다만, 이모티콘 업로드 시, 17~19개 사이 구간에서 HTTP Timeout Exception이 발생하고, 이후로는 업로드가 더이상 진행되지 않으며 Telegram Bot으로의 /getUpdates 경로 요청만 지속적으로 발생하는 문제를 확인하였습니다. 별다른 로그가 뜨는것이 아닌, 단지 Timeout이 발생했다고만 로그가 확인되네요.
다시한번 확인 부탁드리겠습니다.

2023-10-30 23:20 UTC, Coder-Iro commented
일단은 타임아웃을 600초로 늘려놓기는 했는데, 라이브러리가 aiohttp가 아니라 httpx 를 이용해서 network call을 수행하는지라 그거에 따른 속도 저하도 있는 거 같긴 한데... 이건 해결하려면 API 콜을 직접 처리해야 되는 부분이라 시간이 좀 오래걸릴거같네요

2023-10-31 01:28 UTC, yymin1022 approved these changes
TMOUT 600으로는 충분히 이슈없이 잘 동작하는 것 같습니다.
추후 개선하게된다면 어느정도 시간이 지난 뒤에도 업로드가 마무리되지 않으면 텔레그램 서버에 업로드가 지연된다는 안내메시지 정도 하나를 Send하도록 추가하면 어떨까 싶네요!
Merge 하겠습니다. 고생하셨습니다!

2023-10-31 01:28 UTC, merged